### ISSUE TITLE
How did you make it?

### ISSUE THREAD

**Issue by victorsevero** [DevCortez/KaTas#29]
Hello!

First of all, sorry for opening an issue here, I just didn't find a better way to contact any of you.

I'm a brazilian data scientist and I'm really into AI gaming. This project of yours got a lot of my attention because you didn't use libtas to make it work, so here's my question: how did you do it? A solution like that would probably help me a lot in my current project, since it only works with emulators for now. Could any of you contact me through discord? My user is sevs#8921. Thank you!

**Comment by DevCortez** [comment]
Added you there on discord, kc0rtez
